/** @file     OsTask_OIE.c
  * 
  * @brief    Task OsTask_OIE body
  * 
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "OsTask_OIE.h"
#else /* defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
extern CONST(Rte_QTaskType, RTE_DATA) Rte_Queue_CPT_ECU_ABS_P_toSensor_cs_toSensor;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

#define RTE_START_SEC_VAR_8BIT
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
extern VAR(uint8, RTE_DATA) Rte_Var_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor_outstanding;
#define RTE_STOP_SEC_VAR_8BIT
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

/* Runnable entity prototypes */
#define ECU_ABS_START_SEC_CODE
#include "ECU_ABS_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, ECU_ABS_CODE) RE_ECU_ABS_func(CONSTP2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) cs_data);
#define ECU_ABS_STOP_SEC_CODE
#include "ECU_ABS_MemMap.h" /*lint !e537 permit multiple inclusion */

#define RTE_START_SEC_TASKBODY
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
TASK(OsTask_OIE)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   {
      /* Box: CPT_ECU_ABS begin */
      /* P_toSensor */
      {
         Rte_CPT_ECU_ABS_P_toSensor_cs_toSensor_RtnQEType cliQEl;
         Std_ReturnType rtn;
         Rte_CPT_ECU_ABS_P_toSensor_cs_toSensor_QEType srvQEl;

         for (;;) {
            rtn = Rte_ReadQueue(&Rte_Queue_CPT_ECU_ABS_P_toSensor_cs_toSensor.cmn, &srvQEl);
            if ( ( ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK) == rtn ) || ( ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_LOST_DATA) == rtn ) )
            {
               cliQEl.cs_data = srvQEl.cs_data;
               /* SpecReq: Measurement point CS begin */
               /* SpecReq: Measurement point CS end */
               RE_ECU_ABS_func(&cliQEl.cs_data);
               /* SpecReq: Measurement point CS begin */
               /* SpecReq: Measurement point CS end */
               Rte_Var_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor_outstanding = FALSE;
               Rte_WriteQueue(srvQEl.clientQueue, &cliQEl);
            }
            else
            {
               break;
            }
         }
      }
      /* Box: CPT_ECU_ABS end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   TerminateTask();
} /* OsTask_OIE */
#define RTE_STOP_SEC_TASKBODY
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

