/** @file     OsTask_2.c
  * 
  * @brief    Task OsTask_2 body
  * 
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "OsTask_2.h"
#else /* defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"

#define RTE_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
extern VAR(Rte_REActCounterType, RTE_DATA) Rte_ActCount_CPT_Status_printf_DRE_event;
#define RTE_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

/* Runnable entity prototypes */
#define Status_printf_START_SEC_CODE
#include "Status_printf_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, Status_printf_CODE) RE_Status_printf_func(void);
#define Status_printf_STOP_SEC_CODE
#include "Status_printf_MemMap.h" /*lint !e537 permit multiple inclusion */

#define RTE_START_SEC_TASKBODY
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
TASK(OsTask_2)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   /* Box: CPT_Status_printf begin */
   if ( Rte_ActCount_CPT_Status_printf_DRE_event != FALSE )
   {
      Rte_ActCount_CPT_Status_printf_DRE_event = FALSE;
      RE_Status_printf_func();
   }
   /* Box: CPT_Status_printf end */
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   TerminateTask();
} /* OsTask_2 */
#define RTE_STOP_SEC_TASKBODY
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

