/** @file     Rte.c
  * 
  * @brief    RTE data structures
  * 
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  */

/* RTE_HEADER_START */

#define RTE_CORE

#ifdef RTE_PREINCLUDE
#include RTE_PREINCLUDE
#endif
/* Box: RTE: OS Headers begin */
#include "Rte_Const.h"
#include "Os.h"
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
/* Box: RTE: OS Headers end */
/* Box: RTE headers begin */
#include <Rte.h>
#include <Rte_Intl.h>
#include <Rte_Main.h>
#include "Rte_Type.h"
#include "Rte_Cfg.h"
#include "Rte_Cbk.h"
#if defined(RTE_REQUIRES_COM)
#include <Com.h>
#endif /* defined(RTE_REQUIRES_COM) */
#if defined(RTE_REQUIRES_NVM)
#include <NvM.h>
#endif /* defined(RTE_REQUIRES_NVM) */
#include "Rte_ECU_ABS.h"
#include "Rte_Sensor_comp.h"
#include "Rte_Status_printf.h"
/* Box: RTE headers end */
/* RTE_HEADER_END */


/* ----- Function and RE prototypes ----- */

/* RTE_FN_PROTOTYPES_START */

/* Global functions */
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_ECU_ABS (CPT_ECU_ABS), Type: ECU_ABS */
#define RTE_START_SEC_CODE
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_Sensor_comp (CPT_Sensor_comp), Type: Sensor_comp */
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Sensor_comp_R_Sensor_comp_cs_toSensor(VAR(uint8, AUTOMATIC) cs_data);
FUNC(Std_ReturnType, RTE_CODE) Rte_Result_Sensor_comp_R_Sensor_comp_cs_toSensor(CONSTP2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) cs_data);
FUNC(Std_ReturnType, RTE_CODE) Rte_Write_Sensor_comp_P_Sensor_comp_sr_toStatus(VAR(uint8, AUTOMATIC) data);
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_Status_printf (CPT_Status_printf), Type: Status_printf */
FUNC(uint8, RTE_CODE) Rte_DRead_Status_printf_R_Status_printf_sr_toStatus(void);
#define RTE_STOP_SEC_CODE
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

/* RTE_FN_PROTOTYPES_END */

/* RTE_RE_PROTOTYPES_START */

/* Type: ECU_ABS */
#define ECU_ABS_START_SEC_CODE
#include "ECU_ABS_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, ECU_ABS_CODE) RE_ECU_ABS_func(CONSTP2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) cs_data);
#define ECU_ABS_STOP_SEC_CODE
#include "ECU_ABS_MemMap.h" /*lint !e537 permit multiple inclusion */
/* Type: Sensor_comp */
#define Sensor_comp_START_SEC_CODE
#include "Sensor_comp_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, Sensor_comp_CODE) RE_Sensor_comp_func(void);
#define Sensor_comp_STOP_SEC_CODE
#include "Sensor_comp_MemMap.h" /*lint !e537 permit multiple inclusion */
/* Type: Status_printf */
#define Status_printf_START_SEC_CODE
#include "Status_printf_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, Status_printf_CODE) RE_Status_printf_func(void);
#define Status_printf_STOP_SEC_CODE
#include "Status_printf_MemMap.h" /*lint !e537 permit multiple inclusion */

/* RTE_RE_PROTOTYPES_END */

/* RTE_SE_PROTOTYPES_START */

/* RTE_SE_PROTOTYPES_END */

/* ----- External variables ----- */

/* RTE_IMPORTS_START */

/* RTE_IMPORTS_END */

/* ----- Global variables ----- */

/* RTE_GLOBALS_START */

#define RTE_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
VAR(Rte_REActCounterType, RTE_DATA) Rte_ActCount_CPT_Status_printf_DRE_event = 0U;
VAR(Rte_CPT_ECU_ABS_P_toSensor_cs_toSensor_QEType, RTE_DATA) Rte_Queue_CPT_ECU_ABS_P_toSensor_cs_toSensor_data[10];
VAR(Rte_QDynType, RTE_DATA) Rte_Queue_CPT_ECU_ABS_P_toSensor_cs_toSensor_dyn = {
   Rte_Queue_CPT_ECU_ABS_P_toSensor_cs_toSensor_data,  /* in */
   Rte_Queue_CPT_ECU_ABS_P_toSensor_cs_toSensor_data,  /* out */
   0U,                                               /* used */
   0U                                                /* lost_data */
};
#define RTE_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
CONST(Rte_QTaskType, RTE_CONST) Rte_Queue_CPT_ECU_ABS_P_toSensor_cs_toSensor = {
   {
      &Rte_Queue_CPT_ECU_ABS_P_toSensor_cs_toSensor_dyn,  /* dynamic */
      1U,                                            /* copy */
      10,                                            /* queue_size */
      sizeof(Rte_CPT_ECU_ABS_P_toSensor_cs_toSensor_QEType),  /* element_size */
      Rte_Queue_CPT_ECU_ABS_P_toSensor_cs_toSensor_data,  /* buffer_start */
      &Rte_Queue_CPT_ECU_ABS_P_toSensor_cs_toSensor_data[10],  /* buffer_end */
      RTE_TASK                                       /* notification_type */
   },                                                /* cmn */
   RTE_REF_FROM_TASK(OsTask_OIE)                     /* task */
};
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

#define RTE_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
VAR(Rte_CPT_ECU_ABS_P_toSensor_cs_toSensor_RtnQEType, RTE_DATA) Rte_Queue_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor_data[1];
VAR(Rte_QDynType, RTE_DATA) Rte_Queue_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor_dynamic = {
   Rte_Queue_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor_data,  /* in */
   Rte_Queue_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor_data,  /* out */
   0U,                                               /* used */
   0U                                                /* lost_data */
};
#define RTE_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
CONST(Rte_QDRAType, RTE_CONST) Rte_Queue_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor = {
   {
      &Rte_Queue_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor_dynamic,  /* dynamic */
      1U,                                            /* copy */
      1U,                                            /* queue_size */
      sizeof(Rte_CPT_ECU_ABS_P_toSensor_cs_toSensor_RtnQEType),  /* element_size */
      Rte_Queue_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor_data,  /* buffer_start */
      &Rte_Queue_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor_data[1],  /* buffer_end */
      RTE_DRA                                        /* notification_type */
   }                                                 /* cmn */
};
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

#if defined(RTE_WOWP_EVENTS) && (RTE_WOWP_EVENTS > 0)
#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
CONST(Rte_TaskInfo, RTE_CONST) Rte_Tasks[3] = {
   { RTE_REF_FROM_TASK(OsTask_2), RTE_NUM_TIMEOUT_ALARMS, 0 },
   { RTE_REF_FROM_TASK(OsTask_OIE), RTE_NUM_TIMEOUT_ALARMS, 0 },
   { RTE_REF_FROM_TASK(OsTask_TE), RTE_NUM_TIMEOUT_ALARMS, 0 }
};
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

#endif /* defined(RTE_WOWP_EVENTS) && (RTE_WOWP_EVENTS > 0) */
#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
CONST(Rte_AlarmRefType, RTE_CONST) Rte_TimeoutAlarms[1] = {
   RTE_REF_FROM_ALARM(Rte_TimeoutAlarm1)
};
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

#define RTE_START_SEC_VAR_8BIT
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
VAR(uint8, RTE_DATA) Rte_Var_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor_outstanding = FALSE;
VAR(uint8, RTE_DATA) sr_toStatus;
#define RTE_STOP_SEC_VAR_8BIT
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
/* RTE_GLOBALS_END */


/* ----- Data structures ----- */

/* RTE_CDS_START */

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_ECU_ABS (CPT_ECU_ABS), Type: ECU_ABS */
CONST(struct Rte_CDS_ECU_ABS, RTE_CONST) Rte_Inst_ECU_ABS = {
   0U                                                /* _dummy */
};
CONST(Rte_SelfType_ECU_ABS, RTE_CONST) Rte_Self_CPT_ECU_ABS = &Rte_Inst_ECU_ABS;
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_Sensor_comp (CPT_Sensor_comp), Type: Sensor_comp */
CONST(struct Rte_CDS_Sensor_comp, RTE_CONST) Rte_Inst_Sensor_comp = {
   0U                                                /* _dummy */
};
CONST(Rte_SelfType_Sensor_comp, RTE_CONST) Rte_Self_CPT_Sensor_comp = &Rte_Inst_Sensor_comp;
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_Status_printf (CPT_Status_printf), Type: Status_printf */
CONST(struct Rte_CDS_Status_printf, RTE_CONST) Rte_Inst_Status_printf = {
   0U                                                /* _dummy */
};
CONST(Rte_SelfType_Status_printf, RTE_CONST) Rte_Self_CPT_Status_printf = &Rte_Inst_Status_printf;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

/* RTE_CDS_END */

/* ----- Function implementations ----- */

/* RTE_FUNCTIONS_START */

/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_ECU_ABS (CPT_ECU_ABS), Type: ECU_ABS */
#define RTE_START_SEC_CODE
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_Sensor_comp (CPT_Sensor_comp), Type: Sensor_comp */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_Sensor_comp_R_Sensor_comp_cs_toSensor(VAR(uint8, AUTOMATIC) cs_data) /* 2 */
{
   VAR(Std_ReturnType, AUTOMATIC) rtn = RTE_E_OK;
   Rte_CPT_ECU_ABS_P_toSensor_cs_toSensor_QEType srvQEl;

   /* SpecReq: Measurement point CS begin */
   /* SpecReq: Measurement point CS end */
   if ( FALSE == Rte_Var_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor_outstanding )
   {
      srvQEl.cs_data = cs_data;
      srvQEl.clientQueue = &Rte_Queue_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor.cmn;
      /* SpecReq: Activate RE via Queue begin */
      Rte_Var_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor_outstanding = TRUE;
      rtn = Rte_WriteQueue(&Rte_Queue_CPT_ECU_ABS_P_toSensor_cs_toSensor.cmn, &srvQEl);
      if ( ((VAR(StatusType, AUTOMATIC))E_OK) != rtn )
      {
         Rte_Var_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor_outstanding = FALSE;
      }
      /* SpecReq: Activate RE via Queue end */
   }
   else
   {
      rtn = RTE_E_LIMIT;
   }
   return rtn;
}

FUNC(Std_ReturnType, RTE_CODE)
Rte_Result_Sensor_comp_R_Sensor_comp_cs_toSensor(CONSTP2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) cs_data) /* 2 */
{
   VAR(Std_ReturnType, AUTOMATIC) rtn;
   Rte_CPT_ECU_ABS_P_toSensor_cs_toSensor_RtnQEType cliQEl;

   rtn = Rte_ReadQueue(&Rte_Queue_CPT_Sensor_comp_R_Sensor_comp_cs_toSensor.cmn, &cliQEl);
   if ( ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK) == rtn )
   {
      (*(cs_data)) = cliQEl.cs_data;
      /* SpecReq: Measurement point CS begin */
      /* SpecReq: Measurement point CS end */
   }
   else
   {
      /* if ( rtn != ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_COM_STOPPED) ) -- skipped as container has no effect */
   }
   return rtn;
}

FUNC(Std_ReturnType, RTE_CODE)
Rte_Write_Sensor_comp_P_Sensor_comp_sr_toStatus(VAR(uint8, AUTOMATIC) data) /* 2 */
{
   VAR(Std_ReturnType, AUTOMATIC) rtn = RTE_E_OK;
   Std_ReturnType tmp;

   rtn = ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK);
   /* Box: Send sr_toStatus to /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_Status_printf.R_Status_printf begin */
   /* SpecReq: Buffer write begin */
   /* Optimizer: optimized resource lock */
   RTE_ATOMIC8(sr_toStatus = data);
   /* SpecReq: Activate RE begin */
   Rte_ActCount_CPT_Status_printf_DRE_event = TRUE;
   tmp = ActivateTask(OsTask_2);
   if ( ( ((VAR(StatusType, AUTOMATIC))E_OK) != tmp ) && ( ((VAR(Std_ReturnType, AUTOMATIC))E_OS_LIMIT) != tmp ) )
   {
      rtn = ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_COM_STOPPED);
   }
   /* SpecReq: Activate RE end */
   /* SpecReq: Buffer write end */
   /* Box: Send sr_toStatus to /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_Status_printf.R_Status_printf end */
   /* Send complete */
   return rtn;
}

/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_Status_printf (CPT_Status_printf), Type: Status_printf */
FUNC(uint8, RTE_CODE)
Rte_DRead_Status_printf_R_Status_printf_sr_toStatus(void) /* 2 */
{
   VAR(uint8, AUTOMATIC) rtn;

   /* SpecReq: Buffer read begin */
   /* Optimizer: optimized resource lock */
   RTE_ATOMIC8(rtn = sr_toStatus);
   /* SpecReq: Buffer read end */
   return rtn;
}

#define RTE_STOP_SEC_CODE
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
/* ----- API functions ----- */

#define RTE_START_SEC_CODE
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
ALARMCALLBACK( Rte_NullAlarmCallback )
{
}

FUNC(void, RTE_CODE)
Rte_Tick_Timeouts(void) /* 1 */
{
   /* SpecReq: TickCounter begin */
#if defined(OSENV_RTAOS40)
   Os_IncrementCounter_Rte_TOutCounter();
#else /* defined(OSENV_RTAOS40) */
   IncrementCounter(((VAR(CounterType, AUTOMATIC))Rte_TOutCounter));
#endif /* defined(OSENV_RTAOS40) */
   /* SpecReq: TickCounter end */
}
#define RTE_STOP_SEC_CODE
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
/* RTE_FUNCTIONS_END */

