/** @file     Rte_Sensor_comp.h
  * 
  * @brief    Application header file
  * 
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  */

#ifndef RTE_SENSOR_COMP_H
#define RTE_SENSOR_COMP_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Sensor_comp_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_RE_Sensor_comp)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_Sensor_comp {
   uint8 _dummy;
};
typedef struct Rte_CDS_Sensor_comp Rte_CDS_Sensor_comp;

/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
extern CONST(struct Rte_CDS_Sensor_comp, RTE_CONST) Rte_Inst_Sensor_comp;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_Sensor_comp, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#define RTE_START_SEC_CODE
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Sensor_comp_R_Sensor_comp_cs_toSensor(VAR(uint8, AUTOMATIC) cs_data);
FUNC(Std_ReturnType, RTE_CODE) Rte_Result_Sensor_comp_R_Sensor_comp_cs_toSensor(CONSTP2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) cs_data);
FUNC(Std_ReturnType, RTE_CODE) Rte_Write_Sensor_comp_P_Sensor_comp_sr_toStatus(VAR(uint8, AUTOMATIC) data);
#define RTE_STOP_SEC_CODE
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_Sensor_comp)
#define Rte_Call_R_Sensor_comp_cs_toSensor( cs_data ) (Rte_Call_Sensor_comp_R_Sensor_comp_cs_toSensor(cs_data))
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_Sensor_comp)
#define Rte_Result_R_Sensor_comp_cs_toSensor( cs_data ) (Rte_Result_Sensor_comp_R_Sensor_comp_cs_toSensor(cs_data))
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_Sensor_comp)
#define Rte_Write_P_Sensor_comp_sr_toStatus( data ) (Rte_Write_Sensor_comp_P_Sensor_comp_sr_toStatus(data))
#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define Sensor_comp_START_SEC_CODE
#include "Sensor_comp_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, Sensor_comp_CODE) RE_Sensor_comp_func(void);
#define Sensor_comp_STOP_SEC_CODE
#include "Sensor_comp_MemMap.h" /*lint !e537 permit multiple inclusion */

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* RTE_SENSOR_COMP_H */
