/** @file     Rte_Status_printf.c
  * 
  * @brief    RTE Sample SWC implementation skeleton file
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  */

#include "Rte_Status_printf.h"
#include "VirtualDevices.h"
/* --------------------------------------------------------------------------- */
/* RTE Event: /Components/Status_printf/IB_Status_printf/DRE_event */

FUNC(void, Status_printf_CODE) RE_Status_printf_func(void)
{
   /* ... */
	int tmp;
	tmp = Rte_DRead_R_Status_printf_sr_toStatus();
	setActuatorLevel(tmp);
	//status_printf("Receiver : %d", tmp);

	//setDrDoorActuator(tmp);
}

