/** @file     Rte_ECU_ABS.c
  * 
  * @brief    RTE Sample SWC implementation skeleton file
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  */

#include "Rte_ECU_ABS.h"
#include "VirtualDevices.h"
/* --------------------------------------------------------------------------- */
/* RTE Event: /Components/ECU_ABS/IB_ECU_ABS/OIE_Invoked */

FUNC(void, ECU_ABS_CODE) RE_ECU_ABS_func(CONSTP2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) cs_data)
{
   /* inout */
	status_printf("operation server : %d", *cs_data);
	*cs_data = AccelSensorValue();
	//*cs_data = 200;

	/*in*/
	//status_printf("operation arg : %d", cs_data);


	/*out */
	//*cs_data=200;

}

