/** @file     OsTask_event.c
  * 
  * @brief    Task OsTask_event body
  * 
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  * 
  * @date     Thu Jan 25 14:23:35 2018
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "OsTask_event.h"
#else /* defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"

#define RTE_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
extern VAR(Rte_REActCounterType, RTE_DATA) Rte_ActCount_CPT_App_swc1_ExternalTriggerOccurredEvent_0;
extern VAR(Rte_REActCounterType, RTE_DATA) Rte_ActCount_CPT_App_swc2_DataReceivedEvent_0;
#define RTE_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

/* Runnable entity prototypes */
#define App_swc1_START_SEC_CODE
#include "App_swc1_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, App_swc1_CODE) RE_trigger_func(void);
#define App_swc1_STOP_SEC_CODE
#include "App_swc1_MemMap.h" /*lint !e537 permit multiple inclusion */
#define App_swc2_START_SEC_CODE
#include "App_swc2_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, App_swc2_CODE) RE_receive_func(void);
#define App_swc2_STOP_SEC_CODE
#include "App_swc2_MemMap.h" /*lint !e537 permit multiple inclusion */

#define RTE_START_SEC_TASKBODY
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
TASK(OsTask_event)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   /* Box: CPT_App_swc1 begin */
   if ( Rte_ActCount_CPT_App_swc1_ExternalTriggerOccurredEvent_0 != FALSE )
   {
      Rte_ActCount_CPT_App_swc1_ExternalTriggerOccurredEvent_0 = FALSE;
      RE_trigger_func();
   }
   /* Box: CPT_App_swc1 end */
   /* Box: CPT_App_swc2 begin */
   if ( Rte_ActCount_CPT_App_swc2_DataReceivedEvent_0 != FALSE )
   {
      Rte_ActCount_CPT_App_swc2_DataReceivedEvent_0 = FALSE;
      RE_receive_func();
   }
   /* Box: CPT_App_swc2 end */
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   TerminateTask();
} /* OsTask_event */
#define RTE_STOP_SEC_TASKBODY
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

