/** @file     Rte.c
  * 
  * @brief    RTE data structures
  * 
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  * 
  * @date     Thu Jan 25 14:23:35 2018
  */

/* RTE_HEADER_START */

#define RTE_CORE

#ifdef RTE_PREINCLUDE
#include RTE_PREINCLUDE
#endif
/* Box: RTE: OS Headers begin */
#include "Rte_Const.h"
#include "Os.h"
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
/* Box: RTE: OS Headers end */
/* Box: RTE headers begin */
#include <Rte.h>
#include <Rte_Intl.h>
#include <Rte_Main.h>
#include "Rte_Type.h"
#include "Rte_Cfg.h"
#include "Rte_Cbk.h"
#if defined(RTE_REQUIRES_COM)
#include <Com.h>
#endif /* defined(RTE_REQUIRES_COM) */
#if defined(RTE_REQUIRES_NVM)
#include <NvM.h>
#endif /* defined(RTE_REQUIRES_NVM) */
#include "Rte_App_swc1.h"
#include "Rte_App_swc2.h"
#include "Rte_ECU_ABS.h"
#include "Rte_Sensor_swc.h"
/* Box: RTE headers end */
/* RTE_HEADER_END */


/* ----- Function and RE prototypes ----- */

/* RTE_FN_PROTOTYPES_START */

/* Global functions */
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_App_swc1 (CPT_App_swc1), Type: App_swc1 */
#define RTE_START_SEC_CODE
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_App_swc2 (CPT_App_swc2), Type: App_swc2 */
FUNC(uint8, RTE_CODE) Rte_DRead_App_swc2_R_receive_sr_test(void);
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_ECU_ABS (CPT_ECU_ABS), Type: ECU_ABS */
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_Sensor_swc (CPT_Sensor_swc), Type: Sensor_swc */
FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Sensor_swc_R_client_cs_test(VAR(uint8, AUTOMATIC) test_1,
                                                                    CONSTP2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) test_2);
FUNC(uint8, RTE_CODE) Rte_IrvRead_Sensor_swc_RE_sensor_2_Explicit_VariableDataPrototype_0(void);
FUNC(void, RTE_CODE) Rte_IrvWrite_Sensor_swc_RE_sensor_1_Explicit_VariableDataPrototype_0(VAR(uint8, AUTOMATIC) data);
FUNC(void, RTE_CODE) Rte_Trigger_Sensor_swc_P_trigger_tr_test(void);
FUNC(Std_ReturnType, RTE_CODE) Rte_Write_Sensor_swc_P_send_sr_test(VAR(uint8, AUTOMATIC) data);
#define RTE_STOP_SEC_CODE
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

/* RTE_FN_PROTOTYPES_END */

/* RTE_RE_PROTOTYPES_START */

/* Type: App_swc1 */
#define App_swc1_START_SEC_CODE
#include "App_swc1_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, App_swc1_CODE) RE_trigger_func(void);
#define App_swc1_STOP_SEC_CODE
#include "App_swc1_MemMap.h" /*lint !e537 permit multiple inclusion */
/* Type: App_swc2 */
#define App_swc2_START_SEC_CODE
#include "App_swc2_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, App_swc2_CODE) RE_receive_func(void);
#define App_swc2_STOP_SEC_CODE
#include "App_swc2_MemMap.h" /*lint !e537 permit multiple inclusion */
/* Type: ECU_ABS */
#define ECU_ABS_START_SEC_CODE
#include "ECU_ABS_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, ECU_ABS_CODE) RE_server_func(VAR(uint8, AUTOMATIC) test_1,
                                        CONSTP2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) test_2);
#define ECU_ABS_STOP_SEC_CODE
#include "ECU_ABS_MemMap.h" /*lint !e537 permit multiple inclusion */
/* Type: Sensor_swc */
#define Sensor_swc_START_SEC_CODE
#include "Sensor_swc_MemMap.h" /*lint !e537 permit multiple inclusion */
FUNC(void, Sensor_swc_CODE) RE_sensor_1_func(void);
FUNC(void, Sensor_swc_CODE) RE_sensor_2_func(void);
#define Sensor_swc_STOP_SEC_CODE
#include "Sensor_swc_MemMap.h" /*lint !e537 permit multiple inclusion */

/* RTE_RE_PROTOTYPES_END */

/* RTE_SE_PROTOTYPES_START */

/* RTE_SE_PROTOTYPES_END */

/* ----- External variables ----- */

/* RTE_IMPORTS_START */

/* RTE_IMPORTS_END */

/* ----- Global variables ----- */

/* RTE_GLOBALS_START */

#define RTE_START_SEC_VAR_8BIT
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
VAR(uint8, RTE_DATA) CPT_Sensor_swc_IB_Sensor_swc_Explicit_VariableDataPrototype_0;
#define RTE_STOP_SEC_VAR_8BIT
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

#define RTE_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
VAR(Rte_REActCounterType, RTE_DATA) Rte_ActCount_CPT_App_swc1_ExternalTriggerOccurredEvent_0 = 0U;
VAR(Rte_REActCounterType, RTE_DATA) Rte_ActCount_CPT_App_swc2_DataReceivedEvent_0 = 0U;
#define RTE_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

#if defined(RTE_WOWP_EVENTS) && (RTE_WOWP_EVENTS > 0)
#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
CONST(Rte_TaskInfo, RTE_CONST) Rte_Tasks[3] = {
   { RTE_REF_FROM_TASK(OsTask_100ms), RTE_NUM_TIMEOUT_ALARMS, 0 },
   { RTE_REF_FROM_TASK(OsTask_event), RTE_NUM_TIMEOUT_ALARMS, 0 },
   { RTE_REF_FROM_TASK(OsTask_10ms), RTE_NUM_TIMEOUT_ALARMS, 0 }
};
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

#endif /* defined(RTE_WOWP_EVENTS) && (RTE_WOWP_EVENTS > 0) */
#define RTE_START_SEC_VAR_8BIT
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
VAR(uint8, RTE_DATA) sr_test;
#define RTE_STOP_SEC_VAR_8BIT
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
/* RTE_GLOBALS_END */


/* ----- Data structures ----- */

/* RTE_CDS_START */

#define RTE_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_App_swc1 (CPT_App_swc1), Type: App_swc1 */
CONST(struct Rte_CDS_App_swc1, RTE_CONST) Rte_Inst_App_swc1 = {
   0U                                                /* _dummy */
};
CONST(Rte_SelfType_App_swc1, RTE_CONST) Rte_Self_CPT_App_swc1 = &Rte_Inst_App_swc1;
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_App_swc2 (CPT_App_swc2), Type: App_swc2 */
CONST(struct Rte_CDS_App_swc2, RTE_CONST) Rte_Inst_App_swc2 = {
   0U                                                /* _dummy */
};
CONST(Rte_SelfType_App_swc2, RTE_CONST) Rte_Self_CPT_App_swc2 = &Rte_Inst_App_swc2;
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_ECU_ABS (CPT_ECU_ABS), Type: ECU_ABS */
CONST(struct Rte_CDS_ECU_ABS, RTE_CONST) Rte_Inst_ECU_ABS = {
   0U                                                /* _dummy */
};
CONST(Rte_SelfType_ECU_ABS, RTE_CONST) Rte_Self_CPT_ECU_ABS = &Rte_Inst_ECU_ABS;
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_Sensor_swc (CPT_Sensor_swc), Type: Sensor_swc */
CONST(struct Rte_CDS_Sensor_swc, RTE_CONST) Rte_Inst_Sensor_swc = {
   0U                                                /* _dummy */
};
CONST(Rte_SelfType_Sensor_swc, RTE_CONST) Rte_Self_CPT_Sensor_swc = &Rte_Inst_Sensor_swc;
#define RTE_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /*lint !e537 permit multiple inclusion */

/* RTE_CDS_END */

/* ----- Function implementations ----- */

/* RTE_FUNCTIONS_START */

/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_App_swc1 (CPT_App_swc1), Type: App_swc1 */
#define RTE_START_SEC_CODE
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_App_swc2 (CPT_App_swc2), Type: App_swc2 */
FUNC(uint8, RTE_CODE)
Rte_DRead_App_swc2_R_receive_sr_test(void) /* 2 */
{
   VAR(uint8, AUTOMATIC) rtn;

   /* SpecReq: Buffer read begin */
   /* Optimizer: optimized resource lock */
   RTE_ATOMIC8(rtn = sr_test);
   /* SpecReq: Buffer read end */
   return rtn;
}

/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_ECU_ABS (CPT_ECU_ABS), Type: ECU_ABS */
/* Instance: /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_Sensor_swc (CPT_Sensor_swc), Type: Sensor_swc */
/* Direct API 'Rte_Call_R_client_cs_test' for 'CPT_Sensor_swc' optimized to an inline call. */
/* Function body emitted - SW-C is delivered as object-code. */
FUNC(Std_ReturnType, RTE_CODE)
Rte_Call_Sensor_swc_R_client_cs_test(VAR(uint8, AUTOMATIC) test_1,
                                     CONSTP2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) test_2) /* 1 */
{
   VAR(Std_ReturnType, AUTOMATIC) rtn;

   /* SpecReq: Measurement point CS begin */
   /* SpecReq: Measurement point CS end */
   /* SpecReq: Activate RE via Queue begin */
   /* Parameter test_1 has direction IN */
   /* Parameter test_2 has direction OUT */
   RE_server_func(test_1, test_2);
   rtn = ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK);
   /* SpecReq: Measurement point CS begin */
   /* SpecReq: Measurement point CS end */
   /* SpecReq: Activate RE via Queue end */
   return rtn;
}

/* Direct API 'Rte_IrvRead_RE_sensor_2_Explicit_VariableDataPrototype_0' for 'CPT_Sensor_swc' optimized to direct data read. */
/* Function body emitted - SW-C is delivered as object-code. */
FUNC(uint8, RTE_CODE)
Rte_IrvRead_Sensor_swc_RE_sensor_2_Explicit_VariableDataPrototype_0(void) /* 1 */
{
   VAR(uint8, AUTOMATIC) rtn;

   rtn = CPT_Sensor_swc_IB_Sensor_swc_Explicit_VariableDataPrototype_0;
   return rtn;
}

/* Direct API 'Rte_IrvWrite_RE_sensor_1_Explicit_VariableDataPrototype_0' for 'CPT_Sensor_swc' optimized to direct write. */
/* Function body emitted - SW-C is delivered as object-code. */
FUNC(void, RTE_CODE)
Rte_IrvWrite_Sensor_swc_RE_sensor_1_Explicit_VariableDataPrototype_0(VAR(uint8, AUTOMATIC) data) /* 1 */
{
   RTE_ATOMIC8(CPT_Sensor_swc_IB_Sensor_swc_Explicit_VariableDataPrototype_0 = data);
}

FUNC(void, RTE_CODE)
Rte_Trigger_Sensor_swc_P_trigger_tr_test(void) /* 2 */
{
   /* SpecReq: Activate RE begin */
   Rte_ActCount_CPT_App_swc1_ExternalTriggerOccurredEvent_0 = TRUE;
   ActivateTask(OsTask_event);
   /* SpecReq: Activate RE end */
}

FUNC(Std_ReturnType, RTE_CODE)
Rte_Write_Sensor_swc_P_send_sr_test(VAR(uint8, AUTOMATIC) data) /* 2 */
{
   VAR(Std_ReturnType, AUTOMATIC) rtn = RTE_E_OK;
   Std_ReturnType tmp;

   rtn = ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK);
   /* Box: Send sr_test to /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_App_swc2.R_receive begin */
   /* SpecReq: Buffer write begin */
   /* Optimizer: Removed resource lock for assignment of parameter to global in highest pri task */
   sr_test = data;
   /* SpecReq: Activate RE begin */
   Rte_ActCount_CPT_App_swc2_DataReceivedEvent_0 = TRUE;
   tmp = ActivateTask(OsTask_event);
   if ( ( ((VAR(StatusType, AUTOMATIC))E_OK) != tmp ) && ( ((VAR(Std_ReturnType, AUTOMATIC))E_OS_LIMIT) != tmp ) )
   {
      rtn = ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_COM_STOPPED);
   }
   /* SpecReq: Activate RE end */
   /* SpecReq: Buffer write end */
   /* Box: Send sr_test to /EcuInstance_0_FlatView/SwComponentTypes/EcuInstance_0_FlatView/CPT_App_swc2.R_receive end */
   /* Send complete */
   return rtn;
}

#define RTE_STOP_SEC_CODE
#include "MemMap.h" /*lint !e537 permit multiple inclusion */
/* RTE_FUNCTIONS_END */

