/** @file     Rte_App_swc1.c
  * 
  * @brief    RTE Sample SWC implementation skeleton file
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  * 
  * @date     Thu Jan 25 14:23:35 2018
  */

#include "Rte_App_swc1.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /Components/App_swc1/IB_App_swc1/ExternalTriggerOccurredEvent_0 */

FUNC(void, App_swc1_CODE) RE_trigger_func(void)
{
   /* ... */
}

