/** @file     Rte_Sensor_swc.c
  * 
  * @brief    RTE Sample SWC implementation skeleton file
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  * 
  * @date     Thu Jan 25 14:23:35 2018
  */

#include "Rte_Sensor_swc.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /Components/Sensor_swc/IB_Sensor_swc/TE_100ms */

FUNC(void, Sensor_swc_CODE) RE_sensor_2_func(void)
{
   /* ... */   //Rte_Call_R_client_cs_test()  --header 파일에서 API가져와서 쓰면됨.
	//아래 예시처럼 주고받기.
	int tmp;
	tmp = Rte_IrvRead_RE_sensor_2_Explicit_VariableDataPrototype_0();
	Rte_Write_P_send_sr_test(tmp);
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /Components/Sensor_swc/IB_Sensor_swc/TE_10ms */

FUNC(void, Sensor_swc_CODE) RE_sensor_1_func(void)
{
   /* ... */
	Rte_Call_R_client_cs_test(,test_2);
	int temp;
	temp = test_2;
	Rte_IrvWrite_RE_sensor_1_Explicit_VariableDataPrototype_0(temp);
}

