/** @file     Rte_ECU_ABS.c
  * 
  * @brief    RTE Sample SWC implementation skeleton file
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  * 
  * @date     Thu Jan 25 14:23:35 2018
  */

#include "Rte_ECU_ABS.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /Components/ECU_ABS/IB_ECU_ABS/OperationInvokedEvent_0 */

FUNC(void, ECU_ABS_CODE) RE_server_func(VAR(uint8, AUTOMATIC) test_1,
                                        CONSTP2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) test_2)
{
   /* ... */
}


/*
void RE_server_func(int* test_1, int** test_2){
 위의 함수가 이거와 같다고 생각하면됨. test_1 받아서 나가야되기때문에 pointer로.


}*/