/** @file     Rte_LightAlgo.c
  * 
  * @brief    RTE Sample SWC implementation skeleton file
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  * 
  * @date     Thu Jan 25 11:18:33 2018
  */

#include "Rte_LightAlgo.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /BCU_Light/LightAlgo/IB_LightAlgo/LightStateEvent */

FUNC(void, LightAlgo_CODE) RE_LightAlgo_func(void)
{
   /* ... */
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /BCU_Light/LightAlgo/IB_LightAlgo/TE_100ms_Emergency */

FUNC(void, LightAlgo_CODE) RE_EmergencyLight_func(void)
{
   /* ... */
}

/* --------------------------------------------------------------------------- */
/* RTE Event: /BCU_Light/LightAlgo/IB_LightAlgo/TimingEvent */

FUNC(void, LightAlgo_CODE) RE_LightAlgo2_func(void)
{
   /* ... */
}

