/** @file     Rte_EmergencyButton.c
  * 
  * @brief    RTE Sample SWC implementation skeleton file
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  * 
  * @date     Thu Jan 25 11:18:23 2018
  */

#include "Rte_EmergencyButton.h"

/* --------------------------------------------------------------------------- */
/* RTE Event: /BCU_Light/EmergencyButton/IB_EmergencyButton/TE_100ms */

FUNC(void, EmergencyButton_CODE) RE_EmergencyButton_func(void)
{
   /* ... */
}

