/** @file     Rte_Type.h
  * 
  * @brief    RTE type definitions
  * 
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  * 
  * @note     Generated by ETAS GmbH  RTA-RTE v5.8.4  (R4.0 backend version: v7.8.7 (Build 46772))
  * 
  * @date     Thu Jan 25 11:18:44 2018
  */

#ifndef RTE_TYPE_H
#define RTE_TYPE_H

#include "Rte.h"
#include "Rte_Cfg.h"

/*******************************************************
 ***
 *** Forward Declarations
 ***
 *******************************************************/

struct Rte_CDS_EmergencyManager;

/*******************************************************
 ***
 *** Types
 ***
 *******************************************************/

/* Information: No typedef for ImplementationDataType boolean because the SwBaseType.nativeDeclaration is empty. */

/* Information: No typedef for ImplementationDataType float32 because the SwBaseType.nativeDeclaration is empty. */

/* Information: No typedef for ImplementationDataType float64 because the SwBaseType.nativeDeclaration is empty. */

/* Information: No typedef for ImplementationDataType sint16 because the SwBaseType.nativeDeclaration is empty. */

/* Information: No typedef for ImplementationDataType sint32 because the SwBaseType.nativeDeclaration is empty. */

/* Information: No typedef for ImplementationDataType sint8 because the SwBaseType.nativeDeclaration is empty. */

/* Information: No typedef for ImplementationDataType uint32 because the SwBaseType.nativeDeclaration is empty. */

/* Information: No typedef for ImplementationDataType uint8 because the SwBaseType.nativeDeclaration is empty. */

typedef uint8 I_uint8_0_100;

typedef uint8 I_uint8_0_180;

typedef uint8 I_uint8_0_50;

typedef uint8 I_uint8_97_254;

typedef boolean SIGNAL_QUALIFIER;

typedef uint8 SPEED_WIPING;

typedef boolean STATE_EMERGENCY_BUTTON;

typedef boolean STATE_IGNITION_SWITCH;

typedef boolean STATE_LIGHT;

typedef uint8 STATE_LIGHT_WIP_SWITCH;

typedef uint8 STATE_WIPING;

typedef boolean WIPER_POSITION;

typedef uint8 WP_SPEED;

typedef uint8 WP_WIP;

typedef uint8 WP_WIPER_STATE;

typedef boolean WP_WIP_AUTO;

typedef boolean WP_WIP_MAN;

typedef P2FUNC(VAR(uint8, AUTOMATIC), RTE_CODE, Rte_ModeFP_EmergencyManager_MS_IF_Emergency_EmergencyModeDeclarationGroup) (void);

typedef CONSTP2CONST(struct Rte_CDS_EmergencyManager,AUTOMATIC,RTE_CONST) Rte_SelfType_EmergencyManager;

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_SwitchFP_EmergencyManager_MS_IF_Emergency_EmergencyModeDeclarationGroup) (VAR(uint8, AUTOMATIC) data);

#endif /* !RTE_TYPE_H */
